version: '3'
services:
  frontend:
    image: charansrisai/frontend:latest
    restart: always 
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    image: charansrisai/backend:latest
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always  
    ports:
      - '3001:3001'
    networks:
      - app_network
    environment:
      - JWT_SECRET=SDNCN23423TN394UFKND
      - MONGO_URL=mongodb+srv://charan03:030904@clusterecoverse.xxoya0d.mongodb.net/ecoverse
      - jwt_token=dhfmharnca394020
      - NODE_OPTIONS=--max-old-space-size=4196

networks:
  app_network:
    driver: bridge
